"""make prize redemption idempotency per user

Revision ID: 3b64a9157361
Revises: 7dfe2c29004d
Create Date: 2026-06-04 02:26:38.039311
"""

from collections.abc import Sequence

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401



revision: str = '3b64a9157361'
down_revision: str | Sequence[str] | None = '7dfe2c29004d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prize_redemptions_idempotency_key'), table_name='prize_redemptions')
    op.create_unique_constraint('uq_prize_redemptions_users_id_idempotency_key', 'prize_redemptions', ['users_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_prize_redemptions_users_id_idempotency_key', 'prize_redemptions', type_='unique')
    op.create_index(op.f('ix_prize_redemptions_idempotency_key'), 'prize_redemptions', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###
