"""init

Revision ID: 3f30641b21fe
Revises: 
Create Date: 2026-05-11 12:16:32.864197
"""

from collections.abc import Sequence

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401



revision: str = '3f30641b21fe'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('achievements_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('achievement_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('achievement_type', sa.Enum('referral_milestone', 'daily_streak', 'week_completion', 'quiz_streak', 'monthly_rating', 'project_completion', 'custom', name='achievement_type'), nullable=False),
    sa.Column('repeat_policy', sa.Enum('once', 'weekly', 'monthly', name='achievement_repeat_policy'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('points > 0', name=op.f('ck_achievements_points_positive')),
    sa.PrimaryKeyConstraint('achievements_id', name=op.f('pk_achievements'))
    )
    op.create_index(op.f('ix_achievements_code'), 'achievements', ['code'], unique=True)
    op.create_index(op.f('ix_achievements_is_active'), 'achievements', ['is_active'], unique=False)
    op.create_table('prizes',
    sa.Column('prizes_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prize_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prize_type', sa.Enum('merch', 'promo_code', 'super_prize', 'partner', name='prize_type'), nullable=False),
    sa.Column('receive_type', sa.Enum('pickup', 'delivery', 'promo_code', 'manager_contact', name='prize_receive_type'), nullable=False),
    sa.Column('status', sa.Enum('available', 'sold_out', 'hidden', name='prize_status'), nullable=False),
    sa.Column('cost_points', sa.Integer(), nullable=False),
    sa.Column('quantity_total', sa.Integer(), nullable=True),
    sa.Column('quantity_claimed', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost_points > 0', name=op.f('ck_prizes_cost_points_positive')),
    sa.CheckConstraint('quantity_claimed >= 0', name=op.f('ck_prizes_quantity_claimed_non_negative')),
    sa.CheckConstraint('quantity_total IS NULL OR quantity_claimed <= quantity_total', name=op.f('ck_prizes_quantity_claimed_lte_quantity_total')),
    sa.PrimaryKeyConstraint('prizes_id', name=op.f('pk_prizes'))
    )
    op.create_index(op.f('ix_prizes_code'), 'prizes', ['code'], unique=True)
    op.create_index(op.f('ix_prizes_cost_points'), 'prizes', ['cost_points'], unique=False)
    op.create_index(op.f('ix_prizes_is_active'), 'prizes', ['is_active'], unique=False)
    op.create_table('tasks',
    sa.Column('tasks_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('vk_subscribe', 'vk_like', 'vk_repost', 'vk_comment', 'vk_poll', 'vk_story_mention', 'quiz', 'custom', name='task_type'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repeat_policy', sa.Enum('once', 'daily', 'weekly', name='task_repeat_policy'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('points > 0', name=op.f('ck_tasks_points_positive')),
    sa.CheckConstraint('starts_at IS NULL OR ends_at IS NULL OR starts_at < ends_at', name=op.f('ck_tasks_starts_before_ends')),
    sa.CheckConstraint('week_number IS NULL OR week_number BETWEEN 1 AND 12', name=op.f('ck_tasks_week_number_between_1_and_12')),
    sa.PrimaryKeyConstraint('tasks_id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_code'), 'tasks', ['code'], unique=True)
    op.create_index(op.f('ix_tasks_external_id'), 'tasks', ['external_id'], unique=False)
    op.create_index(op.f('ix_tasks_week_number'), 'tasks', ['week_number'], unique=False)
    op.create_table('users',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('vk_user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vk_screen_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('balance_points', sa.Integer(), nullable=False),
    sa.Column('earned_points_total', sa.Integer(), nullable=False),
    sa.Column('spent_points_total', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance_points >= 0', name=op.f('ck_users_balance_points_non_negative')),
    sa.CheckConstraint('current_level BETWEEN 1 AND 4', name=op.f('ck_users_current_level_between_1_and_4')),
    sa.CheckConstraint('earned_points_total >= 0', name=op.f('ck_users_earned_points_total_non_negative')),
    sa.CheckConstraint('spent_points_total >= 0', name=op.f('ck_users_spent_points_total_non_negative')),
    sa.PrimaryKeyConstraint('users_id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_vk_screen_name'), 'users', ['vk_screen_name'], unique=False)
    op.create_index(op.f('ix_users_vk_user_id'), 'users', ['vk_user_id'], unique=True)
    op.create_table('quiz_questions',
    sa.Column('quiz_questions_id', sa.Integer(), nullable=False),
    sa.Column('tasks_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tasks_id'], ['tasks.tasks_id'], name=op.f('fk_quiz_questions_tasks_id_tasks')),
    sa.PrimaryKeyConstraint('quiz_questions_id', name=op.f('pk_quiz_questions'))
    )
    op.create_index(op.f('ix_quiz_questions_is_active'), 'quiz_questions', ['is_active'], unique=False)
    op.create_index(op.f('ix_quiz_questions_tasks_id'), 'quiz_questions', ['tasks_id'], unique=False)
    op.create_table('transactions',
    sa.Column('transactions_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('tasks_id', sa.Integer(), nullable=True),
    sa.Column('prizes_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('accrual', 'spend', name='transaction_type'), nullable=False),
    sa.Column('transaction_source', sa.Enum('registration', 'task', 'prize', 'referral', 'achievement', 'adjustment', name='transaction_source'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_transactions_amount_positive')),
    sa.CheckConstraint('balance_after >= 0', name=op.f('ck_transactions_balance_after_non_negative')),
    sa.CheckConstraint('balance_before >= 0', name=op.f('ck_transactions_balance_before_non_negative')),
    sa.ForeignKeyConstraint(['prizes_id'], ['prizes.prizes_id'], name=op.f('fk_transactions_prizes_id_prizes')),
    sa.ForeignKeyConstraint(['tasks_id'], ['tasks.tasks_id'], name=op.f('fk_transactions_tasks_id_tasks')),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], name=op.f('fk_transactions_users_id_users')),
    sa.PrimaryKeyConstraint('transactions_id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_prizes_id'), 'transactions', ['prizes_id'], unique=False)
    op.create_index(op.f('ix_transactions_tasks_id'), 'transactions', ['tasks_id'], unique=False)
    op.create_index(op.f('ix_transactions_users_id'), 'transactions', ['users_id'], unique=False)
    op.create_table('user_daily_activities',
    sa.Column('user_daily_activities_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('streak_days > 0', name=op.f('ck_user_daily_activities_streak_days_positive')),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], name=op.f('fk_user_daily_activities_users_id_users')),
    sa.PrimaryKeyConstraint('user_daily_activities_id', name=op.f('pk_user_daily_activities')),
    sa.UniqueConstraint('users_id', 'activity_date', name='uq_user_daily_activities_users_date')
    )
    op.create_index(op.f('ix_user_daily_activities_activity_date'), 'user_daily_activities', ['activity_date'], unique=False)
    op.create_index(op.f('ix_user_daily_activities_users_id'), 'user_daily_activities', ['users_id'], unique=False)
    op.create_table('prize_redemptions',
    sa.Column('prize_redemptions_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('prizes_id', sa.Integer(), nullable=False),
    sa.Column('transactions_id', sa.Integer(), nullable=True),
    sa.Column('prize_redemption_status', sa.Enum('reserved', 'issued', 'canceled', name='prize_redemption_status'), nullable=False),
    sa.Column('receive_type', sa.Enum('pickup', 'delivery', 'promo_code', 'manager_contact', name='prize_receive_type'), nullable=False),
    sa.Column('points_spent', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('points_spent >= 0', name=op.f('ck_prize_redemptions_points_spent_non_negative')),
    sa.ForeignKeyConstraint(['prizes_id'], ['prizes.prizes_id'], name=op.f('fk_prize_redemptions_prizes_id_prizes')),
    sa.ForeignKeyConstraint(['transactions_id'], ['transactions.transactions_id'], name=op.f('fk_prize_redemptions_transactions_id_transactions')),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], name=op.f('fk_prize_redemptions_users_id_users')),
    sa.PrimaryKeyConstraint('prize_redemptions_id', name=op.f('pk_prize_redemptions')),
    sa.UniqueConstraint('transactions_id', name=op.f('uq_prize_redemptions_transactions_id'))
    )
    op.create_index(op.f('ix_prize_redemptions_prizes_id'), 'prize_redemptions', ['prizes_id'], unique=False)
    op.create_index(op.f('ix_prize_redemptions_users_id'), 'prize_redemptions', ['users_id'], unique=False)
    op.create_table('quiz_question_options',
    sa.Column('quiz_question_options_id', sa.Integer(), nullable=False),
    sa.Column('quiz_questions_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_questions_id'], ['quiz_questions.quiz_questions_id'], name=op.f('fk_quiz_question_options_quiz_questions_id_quiz_questions')),
    sa.PrimaryKeyConstraint('quiz_question_options_id', name=op.f('pk_quiz_question_options'))
    )
    op.create_index(op.f('ix_quiz_question_options_quiz_questions_id'), 'quiz_question_options', ['quiz_questions_id'], unique=False)
    op.create_table('referrals',
    sa.Column('referrals_id', sa.Integer(), nullable=False),
    sa.Column('inviter_users_id', sa.Integer(), nullable=False),
    sa.Column('invited_users_id', sa.Integer(), nullable=False),
    sa.Column('bonus_transactions_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('inviter_users_id <> invited_users_id', name=op.f('ck_referrals_different_users')),
    sa.ForeignKeyConstraint(['bonus_transactions_id'], ['transactions.transactions_id'], name=op.f('fk_referrals_bonus_transactions_id_transactions')),
    sa.ForeignKeyConstraint(['invited_users_id'], ['users.users_id'], name=op.f('fk_referrals_invited_users_id_users')),
    sa.ForeignKeyConstraint(['inviter_users_id'], ['users.users_id'], name=op.f('fk_referrals_inviter_users_id_users')),
    sa.PrimaryKeyConstraint('referrals_id', name=op.f('pk_referrals')),
    sa.UniqueConstraint('bonus_transactions_id', name='uq_referrals_bonus_transactions_id'),
    sa.UniqueConstraint('invited_users_id', name='uq_referrals_invited_users_id')
    )
    op.create_index(op.f('ix_referrals_invited_users_id'), 'referrals', ['invited_users_id'], unique=False)
    op.create_index(op.f('ix_referrals_inviter_users_id'), 'referrals', ['inviter_users_id'], unique=False)
    op.create_table('task_completions',
    sa.Column('task_completions_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('tasks_id', sa.Integer(), nullable=False),
    sa.Column('completion_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transactions_id', sa.Integer(), nullable=True),
    sa.Column('task_completion_status', sa.Enum('pending', 'completed', 'rejected', 'canceled', name='task_completion_status'), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('external_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('evidence_external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tasks_id'], ['tasks.tasks_id'], name=op.f('fk_task_completions_tasks_id_tasks')),
    sa.ForeignKeyConstraint(['transactions_id'], ['transactions.transactions_id'], name=op.f('fk_task_completions_transactions_id_transactions')),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], name=op.f('fk_task_completions_users_id_users')),
    sa.PrimaryKeyConstraint('task_completions_id', name=op.f('pk_task_completions')),
    sa.UniqueConstraint('transactions_id', name=op.f('uq_task_completions_transactions_id')),
    sa.UniqueConstraint('users_id', 'tasks_id', 'completion_key', name='uq_task_completions_users_tasks_key')
    )
    op.create_index(op.f('ix_task_completions_completion_key'), 'task_completions', ['completion_key'], unique=False)
    op.create_index(op.f('ix_task_completions_evidence_external_id'), 'task_completions', ['evidence_external_id'], unique=False)
    op.create_index(op.f('ix_task_completions_external_event_id'), 'task_completions', ['external_event_id'], unique=False)
    op.create_index(op.f('ix_task_completions_tasks_id'), 'task_completions', ['tasks_id'], unique=False)
    op.create_index(op.f('ix_task_completions_users_id'), 'task_completions', ['users_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_achievements_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('achievements_id', sa.Integer(), nullable=False),
    sa.Column('transactions_id', sa.Integer(), nullable=False),
    sa.Column('achievement_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('points_awarded > 0', name=op.f('ck_user_achievements_points_awarded_positive')),
    sa.ForeignKeyConstraint(['achievements_id'], ['achievements.achievements_id'], name=op.f('fk_user_achievements_achievements_id_achievements')),
    sa.ForeignKeyConstraint(['transactions_id'], ['transactions.transactions_id'], name=op.f('fk_user_achievements_transactions_id_transactions')),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], name=op.f('fk_user_achievements_users_id_users')),
    sa.PrimaryKeyConstraint('user_achievements_id', name=op.f('pk_user_achievements')),
    sa.UniqueConstraint('transactions_id', name=op.f('uq_user_achievements_transactions_id')),
    sa.UniqueConstraint('users_id', 'achievements_id', 'achievement_key', name='uq_user_achievements_users_achievements_key')
    )
    op.create_index(op.f('ix_user_achievements_achievement_key'), 'user_achievements', ['achievement_key'], unique=False)
    op.create_index(op.f('ix_user_achievements_achievements_id'), 'user_achievements', ['achievements_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_users_id'), 'user_achievements', ['users_id'], unique=False)
    op.create_table('prize_promo_codes',
    sa.Column('prize_promo_codes_id', sa.Integer(), nullable=False),
    sa.Column('prizes_id', sa.Integer(), nullable=False),
    sa.Column('prize_redemptions_id', sa.Integer(), nullable=True),
    sa.Column('promo_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('promo_code_status', sa.Enum('available', 'reserved', 'issued', 'disabled', name='promo_code_status'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prize_redemptions_id'], ['prize_redemptions.prize_redemptions_id'], name=op.f('fk_prize_promo_codes_prize_redemptions_id_prize_redemptions')),
    sa.ForeignKeyConstraint(['prizes_id'], ['prizes.prizes_id'], name=op.f('fk_prize_promo_codes_prizes_id_prizes')),
    sa.PrimaryKeyConstraint('prize_promo_codes_id', name=op.f('pk_prize_promo_codes')),
    sa.UniqueConstraint('prize_redemptions_id', name=op.f('uq_prize_promo_codes_prize_redemptions_id'))
    )
    op.create_index(op.f('ix_prize_promo_codes_prizes_id'), 'prize_promo_codes', ['prizes_id'], unique=False)
    op.create_index(op.f('ix_prize_promo_codes_promo_code'), 'prize_promo_codes', ['promo_code'], unique=True)
    op.create_index(op.f('ix_prize_promo_codes_promo_code_status'), 'prize_promo_codes', ['promo_code_status'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('quiz_answers_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('quiz_questions_id', sa.Integer(), nullable=False),
    sa.Column('quiz_question_options_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('task_completions_id', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_question_options_id'], ['quiz_question_options.quiz_question_options_id'], name=op.f('fk_quiz_answers_quiz_question_options_id_quiz_question_options')),
    sa.ForeignKeyConstraint(['quiz_questions_id'], ['quiz_questions.quiz_questions_id'], name=op.f('fk_quiz_answers_quiz_questions_id_quiz_questions')),
    sa.ForeignKeyConstraint(['task_completions_id'], ['task_completions.task_completions_id'], name=op.f('fk_quiz_answers_task_completions_id_task_completions')),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], name=op.f('fk_quiz_answers_users_id_users')),
    sa.PrimaryKeyConstraint('quiz_answers_id', name=op.f('pk_quiz_answers')),
    sa.UniqueConstraint('task_completions_id', name=op.f('uq_quiz_answers_task_completions_id')),
    sa.UniqueConstraint('users_id', 'quiz_questions_id', name='uq_quiz_answers_users_question')
    )
    op.create_index(op.f('ix_quiz_answers_quiz_question_options_id'), 'quiz_answers', ['quiz_question_options_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_quiz_questions_id'), 'quiz_answers', ['quiz_questions_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_users_id'), 'quiz_answers', ['users_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_answers_users_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_quiz_questions_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_quiz_question_options_id'), table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index(op.f('ix_prize_promo_codes_promo_code_status'), table_name='prize_promo_codes')
    op.drop_index(op.f('ix_prize_promo_codes_promo_code'), table_name='prize_promo_codes')
    op.drop_index(op.f('ix_prize_promo_codes_prizes_id'), table_name='prize_promo_codes')
    op.drop_table('prize_promo_codes')
    op.drop_index(op.f('ix_user_achievements_users_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievements_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_key'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_task_completions_users_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_tasks_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_external_event_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_evidence_external_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_completion_key'), table_name='task_completions')
    op.drop_table('task_completions')
    op.drop_index(op.f('ix_referrals_inviter_users_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_invited_users_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_quiz_question_options_quiz_questions_id'), table_name='quiz_question_options')
    op.drop_table('quiz_question_options')
    op.drop_index(op.f('ix_prize_redemptions_users_id'), table_name='prize_redemptions')
    op.drop_index(op.f('ix_prize_redemptions_prizes_id'), table_name='prize_redemptions')
    op.drop_table('prize_redemptions')
    op.drop_index(op.f('ix_user_daily_activities_users_id'), table_name='user_daily_activities')
    op.drop_index(op.f('ix_user_daily_activities_activity_date'), table_name='user_daily_activities')
    op.drop_table('user_daily_activities')
    op.drop_index(op.f('ix_transactions_users_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_tasks_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_prizes_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_quiz_questions_tasks_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_is_active'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_users_vk_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_vk_screen_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_week_number'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_external_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_code'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_prizes_is_active'), table_name='prizes')
    op.drop_index(op.f('ix_prizes_cost_points'), table_name='prizes')
    op.drop_index(op.f('ix_prizes_code'), table_name='prizes')
    op.drop_table('prizes')
    op.drop_index(op.f('ix_achievements_is_active'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_code'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
