"""add_code

Revision ID: cbb51be3257d
Revises: 2f41b6a8c9d0
Create Date: 2026-05-29 16:15:04.894152
"""

from collections.abc import Sequence

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401

from sqlalchemy.dialects import postgresql

revision: str = 'cbb51be3257d'
down_revision: str | Sequence[str] | None = '2f41b6a8c9d0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_promo_code_waits',
    sa.Column('task_promo_code_waits_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('tasks_id', sa.Integer(), nullable=False),
    sa.Column('wait_status', sa.Enum('waiting', 'canceled', 'completed', name='task_promo_code_wait_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tasks_id'], ['tasks.tasks_id'], name=op.f('fk_task_promo_code_waits_tasks_id_tasks')),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], name=op.f('fk_task_promo_code_waits_users_id_users')),
    sa.PrimaryKeyConstraint('task_promo_code_waits_id', name=op.f('pk_task_promo_code_waits'))
    )
    op.create_index(op.f('ix_task_promo_code_waits_tasks_id'), 'task_promo_code_waits', ['tasks_id'], unique=False)
    op.create_index(op.f('ix_task_promo_code_waits_users_id'), 'task_promo_code_waits', ['users_id'], unique=False)
    op.create_index('ix_task_promo_code_waits_users_id_status', 'task_promo_code_waits', ['users_id', 'wait_status'], unique=False)
    op.create_index(op.f('ix_task_promo_code_waits_wait_status'), 'task_promo_code_waits', ['wait_status'], unique=False)
    op.create_table('task_promo_codes',
    sa.Column('task_promo_codes_id', sa.Integer(), nullable=False),
    sa.Column('tasks_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('promo_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('promo_code_status', sa.Enum('available', 'used', name='task_promo_code_status'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tasks_id'], ['tasks.tasks_id'], name=op.f('fk_task_promo_codes_tasks_id_tasks')),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], name=op.f('fk_task_promo_codes_users_id_users')),
    sa.PrimaryKeyConstraint('task_promo_codes_id', name=op.f('pk_task_promo_codes')),
    sa.UniqueConstraint('tasks_id', 'promo_code', name='uq_task_promo_codes_tasks_code')
    )
    op.create_index(op.f('ix_task_promo_codes_promo_code'), 'task_promo_codes', ['promo_code'], unique=False)
    op.create_index(op.f('ix_task_promo_codes_promo_code_status'), 'task_promo_codes', ['promo_code_status'], unique=False)
    op.create_index(op.f('ix_task_promo_codes_tasks_id'), 'task_promo_codes', ['tasks_id'], unique=False)
    op.create_index('ix_task_promo_codes_tasks_id_status', 'task_promo_codes', ['tasks_id', 'promo_code_status'], unique=False)
    op.create_index(op.f('ix_task_promo_codes_users_id'), 'task_promo_codes', ['users_id'], unique=False)
    op.drop_index(op.f('ix_prize_promo_codes_prizes_id'), table_name='prize_promo_codes')
    op.drop_index(op.f('ix_prize_promo_codes_promo_code'), table_name='prize_promo_codes')
    op.drop_index(op.f('ix_prize_promo_codes_promo_code_status'), table_name='prize_promo_codes')
    op.drop_table('prize_promo_codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prize_promo_codes',
    sa.Column('prize_promo_codes_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prizes_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prize_redemptions_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('promo_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('promo_code_status', postgresql.ENUM('available', 'reserved', 'issued', 'disabled', name='promo_code_status'), autoincrement=False, nullable=False),
    sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['prize_redemptions_id'], ['prize_redemptions.prize_redemptions_id'], name=op.f('fk_prize_promo_codes_prize_redemptions_id_prize_redemptions')),
    sa.ForeignKeyConstraint(['prizes_id'], ['prizes.prizes_id'], name=op.f('fk_prize_promo_codes_prizes_id_prizes')),
    sa.PrimaryKeyConstraint('prize_promo_codes_id', name=op.f('pk_prize_promo_codes')),
    sa.UniqueConstraint('prize_redemptions_id', name=op.f('uq_prize_promo_codes_prize_redemptions_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_prize_promo_codes_promo_code_status'), 'prize_promo_codes', ['promo_code_status'], unique=False)
    op.create_index(op.f('ix_prize_promo_codes_promo_code'), 'prize_promo_codes', ['promo_code'], unique=True)
    op.create_index(op.f('ix_prize_promo_codes_prizes_id'), 'prize_promo_codes', ['prizes_id'], unique=False)
    op.drop_index(op.f('ix_task_promo_codes_users_id'), table_name='task_promo_codes')
    op.drop_index('ix_task_promo_codes_tasks_id_status', table_name='task_promo_codes')
    op.drop_index(op.f('ix_task_promo_codes_tasks_id'), table_name='task_promo_codes')
    op.drop_index(op.f('ix_task_promo_codes_promo_code_status'), table_name='task_promo_codes')
    op.drop_index(op.f('ix_task_promo_codes_promo_code'), table_name='task_promo_codes')
    op.drop_table('task_promo_codes')
    op.drop_index(op.f('ix_task_promo_code_waits_wait_status'), table_name='task_promo_code_waits')
    op.drop_index('ix_task_promo_code_waits_users_id_status', table_name='task_promo_code_waits')
    op.drop_index(op.f('ix_task_promo_code_waits_users_id'), table_name='task_promo_code_waits')
    op.drop_index(op.f('ix_task_promo_code_waits_tasks_id'), table_name='task_promo_code_waits')
    op.drop_table('task_promo_code_waits')
    # ### end Alembic commands ###
