"""add_pro_priz

Revision ID: da6acdb09873
Revises: cbb51be3257d
Create Date: 2026-05-30 02:34:05.493911
"""

from collections.abc import Sequence

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401



revision: str = 'da6acdb09873'
down_revision: str | Sequence[str] | None = 'cbb51be3257d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prize_redemptions', sa.Column('refund_transactions_id', sa.Integer(), nullable=True))
    op.add_column('prize_redemptions', sa.Column('redemption_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('prize_redemptions', sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('prize_redemptions', sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prize_redemptions', sa.Column('cancel_reason', sa.Text(), nullable=True))
    op.alter_column('prize_redemptions', 'transactions_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_prize_redemptions_idempotency_key'), 'prize_redemptions', ['idempotency_key'], unique=True)
    op.create_index('ix_prize_redemptions_prizes_id_status', 'prize_redemptions', ['prizes_id', 'prize_redemption_status'], unique=False)
    op.create_index(op.f('ix_prize_redemptions_redemption_code'), 'prize_redemptions', ['redemption_code'], unique=True)
    op.create_index('ix_prize_redemptions_status_created_at', 'prize_redemptions', ['prize_redemption_status', 'created_at'], unique=False)
    op.create_index('ix_prize_redemptions_users_id_status', 'prize_redemptions', ['users_id', 'prize_redemption_status'], unique=False)
    op.create_unique_constraint(op.f('uq_prize_redemptions_refund_transactions_id'), 'prize_redemptions', ['refund_transactions_id'])
    op.create_foreign_key(op.f('fk_prize_redemptions_refund_transactions_id_transactions'), 'prize_redemptions', 'transactions', ['refund_transactions_id'], ['transactions_id'])
    op.alter_column('prizes', 'quantity_total',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prizes', 'quantity_total',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_prize_redemptions_refund_transactions_id_transactions'), 'prize_redemptions', type_='foreignkey')
    op.drop_constraint(op.f('uq_prize_redemptions_refund_transactions_id'), 'prize_redemptions', type_='unique')
    op.drop_index('ix_prize_redemptions_users_id_status', table_name='prize_redemptions')
    op.drop_index('ix_prize_redemptions_status_created_at', table_name='prize_redemptions')
    op.drop_index(op.f('ix_prize_redemptions_redemption_code'), table_name='prize_redemptions')
    op.drop_index('ix_prize_redemptions_prizes_id_status', table_name='prize_redemptions')
    op.drop_index(op.f('ix_prize_redemptions_idempotency_key'), table_name='prize_redemptions')
    op.alter_column('prize_redemptions', 'transactions_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('prize_redemptions', 'cancel_reason')
    op.drop_column('prize_redemptions', 'canceled_at')
    op.drop_column('prize_redemptions', 'idempotency_key')
    op.drop_column('prize_redemptions', 'redemption_code')
    op.drop_column('prize_redemptions', 'refund_transactions_id')
    # ### end Alembic commands ###
